### ISSUE TITLE
Older versions of Spark broken via commit 5b82a35

### ISSUE THREAD

**Issue by mikegreiling** [sparkphp/adr#8]
Spark's `composer.json` requires `adr ~0.2` in all versions between 0.4.0 and 0.9.0, which effectively means `adr >=0.2 <1.0.0`.  This means sparkphp/spark versions prior to 0.10.0 without an existing composer.lock are trying to load the latest adr v0.4 which no longer include the `Input` class.

see: https://github.com/sparkphp/spark/blob/v0.7.0/composer.json#L23

Recommendations:
- revert these changes and move breaking changes to the next major version 1.x.x
- if breaking changes are to be introduced in minor version updates going forward, include three decimal places in the composer.json requirements for spark.

i.e.
```
    "require": {
        "sparkphp/adr": "~0.4.0" // >=0.4.0 <0.5.0
    }
```
instead of 
```
    "require": {
        "sparkphp/adr": "~0.4" // >=0.4 <1.0.0
    }
```

Since this is a pre-1.0 release framework, I suppose it may be nitpicking to revert these changes, but either way I thought it worth bringing up.

**Comment by shadowhand** [comment]
As per [semver](http://semver.org/) the `0.x` version may introduce breaking changes:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

That said, it is not my intention to break anyone's installations. Since version `0.10` the version constraint  is more specific: https://github.com/sparkphp/spark/blob/0.10.0/composer.json
